### ISSUE TITLE
does not show up in tier 2 menu.

### ISSUE THREAD

**Issue by yodika** [scruffydogflame/StartWithVehicles#3]
i have the mod instaled but when i goto podstation to research and unlock vehicles it does not show???

**Comment by clairenheit** [comment]
Likely caused by another mod messing with the HUB menu. On a clean save with just this mod installed it shows up just fine.

**Comment by yodika** [comment]
is it possible to get fixed? is there a hub menu mod that can have different menus or switch types/combine???

**Comment by clairenheit** [comment]
Still not entirely sure what the issue you're having is, have you made sure you can't just scroll the menu to the right? I set the priority of the milestone pretty low so it should show up at the end of the list of milestones, so if you have a lot of mods they may have pushed it off to the right. If you could attach a screenshot of your hub tier 2 list it might clear up what's going on a bit more.

**Comment by yodika** [comment]
i will get a screenshot hold on

**Comment by yodika** [comment]
oh ok my faul;t i didnt see the bar, im blind LOL! everything fine its all there, thank you for helping.

**Comment by clairenheit** [comment]
No problem, that's exactly why Github lets you open issues lol! Take care
