### ISSUE TITLE
Nitpick: Mod version number

### ISSUE THREAD

**Issue by budak7273** [scruffydogflame/StartWithVehicles#4]
I suggest that the next release of your mod be SemVersion `1.0.0` as [described on the docs](https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/ReleaseMod.html#:~:text=As%20a%20rule%20of%20thumb%2C%20version%201.0.0%20should%20be%20used%20for%20the%20first%20public%20release%20of%20your%20mod). The reason behind this is tied to SemVer dependency logic rules for versions less than `1.0.0`. If someone wanted to make a modpack or another mod that depends on yours, they would normally use the version range `^0.1.9` (as of the time of posting). This would break if you were to release version `0.2.0` or version `0.1.10` - they would not be considered compatible. With version `1.0.0`, then the version range of `^1.0.0` would allow version `1.0.1`. More info on this [here](https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/ReleaseMod.html#:~:text=However%2C%20it%20functions%20differently%20when%20the%20major%20version%20(the%201%20in%201.2.3)%20is%200%2C%20so%20be%20sure%20that%20your%20major%20version%20is%20at%20least%201%20to%20avoid%20this.).

Also, if you are on the modding discord, it would be great if you could add your discord username to the modpage so people can easily contact you.

**Comment by clairenheit** [comment]
Appreciate the feedback, I was unaware of those rules and I will update the SemVer appropriately should I release another version for whatever reason, I will say however I kind of doubt anyone will ever list this mod as a dependency to theirs given its simplicity. I direct people to github as I often cannot respond immediately to an issue as I'm a busy college student, so if there's problems it helps me to have them organized and waiting for my attention here.

**Comment by budak7273** [comment]
Thanks for the quick turnaround, and good luck with your college work!
